; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	F:\20120709_Enterprise_CT_V2.0_workspace\VC2008_PopPad3_c\.csdata\src\build\PopFind_7.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BP@KBOLAHKL@struct?5PopFindValidFind_csut0p?$AA@ ; `string'
PUBLIC	??_C@_0BH@EHLGHBDH@PopFindValidFind_csut0?$AA@	; `string'
PUBLIC	_PopFindValidFind_csut0
PUBLIC	??_C@_0CB@NAPKLCJI@struct?5PopFindReplaceText_csut0p@ ; `string'
PUBLIC	??_C@_0BJ@GIPAEBMG@PopFindReplaceText_csut0?$AA@ ; `string'
PUBLIC	_PopFindReplaceText_csut0
PUBLIC	??_C@_0CA@JDCEDHBJ@struct?5PopFindReplaceDlg_csut0p?$AA@ ; `string'
PUBLIC	??_C@_0BI@ELODJIJC@PopFindReplaceDlg_csut0?$AA@	; `string'
PUBLIC	_PopFindReplaceDlg_csut0
PUBLIC	??_C@_0BO@HJNJCFN@struct?5PopFindNextText_csut0p?$AA@ ; `string'
PUBLIC	??_C@_0BG@IFGJBCMH@PopFindNextText_csut0?$AA@	; `string'
PUBLIC	_PopFindNextText_csut0
PUBLIC	??_C@_0BO@BLAMHFPG@struct?5PopFindFindText_csut0p?$AA@ ; `string'
PUBLIC	??_C@_0BG@HIOPNLJG@PopFindFindText_csut0?$AA@	; `string'
PUBLIC	_PopFindFindText_csut0
PUBLIC	??_C@_0BN@EFANFKJ@struct?5PopFindFindDlg_csut0p?$AA@ ; `string'
PUBLIC	??_C@_0BF@IOADJCAI@PopFindFindDlg_csut0?$AA@	; `string'
PUBLIC	_PopFindFindDlg_csut0
PUBLIC	__TFX_testFunctionsFor_2814749767106560
PUBLIC	__TFX_testFunctionsFor_3096224743817216
PUBLIC	__TFX_testFunctionsFor_3377699720527872
PUBLIC	__TFX_testFunctionsFor_3659174697238528
PUBLIC	__TFX_testFunctionsFor_3940649673949184
PUBLIC	__TFX_testFunctionsFor_4222124650659840
;	COMDAT ??_C@_0BP@KBOLAHKL@struct?5PopFindValidFind_csut0p?$AA@
CONST	SEGMENT
??_C@_0BP@KBOLAHKL@struct?5PopFindValidFind_csut0p?$AA@ DB 'struct PopFin'
	DB	'dValidFind_csut0p', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BH@EHLGHBDH@PopFindValidFind_csut0?$AA@
CONST	SEGMENT
??_C@_0BH@EHLGHBDH@PopFindValidFind_csut0?$AA@ DB 'PopFindValidFind_csut0'
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0CB@NAPKLCJI@struct?5PopFindReplaceText_csut0p@
CONST	SEGMENT
??_C@_0CB@NAPKLCJI@struct?5PopFindReplaceText_csut0p@ DB 'struct PopFindR'
	DB	'eplaceText_csut0p', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BJ@GIPAEBMG@PopFindReplaceText_csut0?$AA@
CONST	SEGMENT
??_C@_0BJ@GIPAEBMG@PopFindReplaceText_csut0?$AA@ DB 'PopFindReplaceText_c'
	DB	'sut0', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0CA@JDCEDHBJ@struct?5PopFindReplaceDlg_csut0p?$AA@
CONST	SEGMENT
??_C@_0CA@JDCEDHBJ@struct?5PopFindReplaceDlg_csut0p?$AA@ DB 'struct PopFi'
	DB	'ndReplaceDlg_csut0p', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BI@ELODJIJC@PopFindReplaceDlg_csut0?$AA@
CONST	SEGMENT
??_C@_0BI@ELODJIJC@PopFindReplaceDlg_csut0?$AA@ DB 'PopFindReplaceDlg_csu'
	DB	't0', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0BO@HJNJCFN@struct?5PopFindNextText_csut0p?$AA@
CONST	SEGMENT
??_C@_0BO@HJNJCFN@struct?5PopFindNextText_csut0p?$AA@ DB 'struct PopFindN'
	DB	'extText_csut0p', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@IFGJBCMH@PopFindNextText_csut0?$AA@
CONST	SEGMENT
??_C@_0BG@IFGJBCMH@PopFindNextText_csut0?$AA@ DB 'PopFindNextText_csut0', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BO@BLAMHFPG@struct?5PopFindFindText_csut0p?$AA@
CONST	SEGMENT
??_C@_0BO@BLAMHFPG@struct?5PopFindFindText_csut0p?$AA@ DB 'struct PopFind'
	DB	'FindText_csut0p', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@HIOPNLJG@PopFindFindText_csut0?$AA@
CONST	SEGMENT
??_C@_0BG@HIOPNLJG@PopFindFindText_csut0?$AA@ DB 'PopFindFindText_csut0', 00H ; `string'
CONST	ENDS
_DATA	SEGMENT
__TFX_testFunctionsFor_2814749767106560 DD 04H
	DD	FLAT:_PopFindFindDlg_csut0
	DD	FLAT:??_C@_0BF@IOADJCAI@PopFindFindDlg_csut0?$AA@
	DD	FLAT:??_C@_0BN@EFANFKJ@struct?5PopFindFindDlg_csut0p?$AA@
	DD	08H
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
__TFX_testFunctionsFor_3096224743817216 DD 04H
	DD	FLAT:_PopFindFindText_csut0
	DD	FLAT:??_C@_0BG@HIOPNLJG@PopFindFindText_csut0?$AA@
	DD	FLAT:??_C@_0BO@BLAMHFPG@struct?5PopFindFindText_csut0p?$AA@
	DD	0cH
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
__TFX_testFunctionsFor_3377699720527872 DD 04H
	DD	FLAT:_PopFindNextText_csut0
	DD	FLAT:??_C@_0BG@IFGJBCMH@PopFindNextText_csut0?$AA@
	DD	FLAT:??_C@_0BO@HJNJCFN@struct?5PopFindNextText_csut0p?$AA@
	DD	0cH
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
__TFX_testFunctionsFor_3659174697238528 DD 04H
	DD	FLAT:_PopFindReplaceDlg_csut0
	DD	FLAT:??_C@_0BI@ELODJIJC@PopFindReplaceDlg_csut0?$AA@
	DD	FLAT:??_C@_0CA@JDCEDHBJ@struct?5PopFindReplaceDlg_csut0p?$AA@
	DD	08H
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
__TFX_testFunctionsFor_3940649673949184 DD 04H
	DD	FLAT:_PopFindReplaceText_csut0
	DD	FLAT:??_C@_0BJ@GIPAEBMG@PopFindReplaceText_csut0?$AA@
	DD	FLAT:??_C@_0CB@NAPKLCJI@struct?5PopFindReplaceText_csut0p@
	DD	0cH
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
__TFX_testFunctionsFor_4222124650659840 DD 04H
	DD	FLAT:_PopFindValidFind_csut0
	DD	FLAT:??_C@_0BH@EHLGHBDH@PopFindValidFind_csut0?$AA@
	DD	FLAT:??_C@_0BP@KBOLAHKL@struct?5PopFindValidFind_csut0p?$AA@
	DD	08H
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
_DATA	ENDS
;	COMDAT ??_C@_0BN@EFANFKJ@struct?5PopFindFindDlg_csut0p?$AA@
CONST	SEGMENT
??_C@_0BN@EFANFKJ@struct?5PopFindFindDlg_csut0p?$AA@ DB 'struct PopFindFi'
	DB	'ndDlg_csut0p', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BF@IOADJCAI@PopFindFindDlg_csut0?$AA@
CONST	SEGMENT
??_C@_0BF@IOADJCAI@PopFindFindDlg_csut0?$AA@ DB 'PopFindFindDlg_csut0', 00H ; `string'
CONST	ENDS
PUBLIC	_PopFindFindDlg
EXTRN	__imp__FindTextA@4:PROC
EXTRN	_csut_TFX_CoverageBuffer:DWORD
EXTRN	_csut_TFX_LastProbe:DWORD
_BSS	SEGMENT
_szFindText DB	0100H DUP (?)
?fr@?1??PopFindFindDlg@@9@9 DB 028H DUP (?)		; `PopFindFindDlg'::`2'::fr
; Function compile flags: /Ogtpy
_BSS	ENDS
;	COMDAT _PopFindFindDlg
_TEXT	SEGMENT
_hwnd$ = 8						; size = 4
_PopFindFindDlg PROC					; COMDAT
; File d:\open source\vs2008\c\poppad3\popfind.c
; Line 17
	mov	eax, DWORD PTR _csut_TFX_LastProbe
; Line 21
	mov	edx, DWORD PTR _hwnd$[esp-4]
	mov	DWORD PTR [eax], 39			; 00000027H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+39], 49			; 00000031H
; Line 22
	xor	eax, eax
	mov	DWORD PTR ?fr@?1??PopFindFindDlg@@9@9+4, edx
; Line 26
	mov	ecx, 256				; 00000100H
; Line 27
	xor	edx, edx
; Line 32
	push	OFFSET ?fr@?1??PopFindFindDlg@@9@9
	mov	DWORD PTR ?fr@?1??PopFindFindDlg@@9@9, 40 ; 00000028H
	mov	DWORD PTR ?fr@?1??PopFindFindDlg@@9@9+8, eax
	mov	DWORD PTR ?fr@?1??PopFindFindDlg@@9@9+12, 114688 ; 0001c000H
	mov	DWORD PTR ?fr@?1??PopFindFindDlg@@9@9+16, OFFSET _szFindText
	mov	DWORD PTR ?fr@?1??PopFindFindDlg@@9@9+20, eax
	mov	WORD PTR ?fr@?1??PopFindFindDlg@@9@9+24, cx
	mov	WORD PTR ?fr@?1??PopFindFindDlg@@9@9+26, dx
	mov	DWORD PTR ?fr@?1??PopFindFindDlg@@9@9+28, eax
	mov	DWORD PTR ?fr@?1??PopFindFindDlg@@9@9+32, eax
	mov	DWORD PTR ?fr@?1??PopFindFindDlg@@9@9+36, eax
	call	DWORD PTR __imp__FindTextA@4
	mov	ecx, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [ecx], 40			; 00000028H
	mov	edx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [edx+40], 49			; 00000031H
; Line 33
	ret	0
_PopFindFindDlg ENDP
_TEXT	ENDS
PUBLIC	_PopFindReplaceDlg
EXTRN	__imp__ReplaceTextA@4:PROC
_BSS	SEGMENT
_szReplText DB	0100H DUP (?)
?fr@?1??PopFindReplaceDlg@@9@9 DB 028H DUP (?)		; `PopFindReplaceDlg'::`2'::fr
; Function compile flags: /Ogtpy
_BSS	ENDS
;	COMDAT _PopFindReplaceDlg
_TEXT	SEGMENT
_hwnd$ = 8						; size = 4
_PopFindReplaceDlg PROC					; COMDAT
; Line 42
	mov	eax, DWORD PTR _csut_TFX_LastProbe
; Line 46
	mov	edx, DWORD PTR _hwnd$[esp-4]
	mov	DWORD PTR [eax], 41			; 00000029H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+41], 49			; 00000031H
; Line 47
	xor	eax, eax
; Line 51
	mov	ecx, 256				; 00000100H
	mov	DWORD PTR ?fr@?1??PopFindReplaceDlg@@9@9+4, edx
; Line 52
	mov	edx, ecx
; Line 57
	push	OFFSET ?fr@?1??PopFindReplaceDlg@@9@9
	mov	DWORD PTR ?fr@?1??PopFindReplaceDlg@@9@9, 40 ; 00000028H
	mov	DWORD PTR ?fr@?1??PopFindReplaceDlg@@9@9+8, eax
	mov	DWORD PTR ?fr@?1??PopFindReplaceDlg@@9@9+12, 114688 ; 0001c000H
	mov	DWORD PTR ?fr@?1??PopFindReplaceDlg@@9@9+16, OFFSET _szFindText
	mov	DWORD PTR ?fr@?1??PopFindReplaceDlg@@9@9+20, OFFSET _szReplText
	mov	WORD PTR ?fr@?1??PopFindReplaceDlg@@9@9+24, cx
	mov	WORD PTR ?fr@?1??PopFindReplaceDlg@@9@9+26, dx
	mov	DWORD PTR ?fr@?1??PopFindReplaceDlg@@9@9+28, eax
	mov	DWORD PTR ?fr@?1??PopFindReplaceDlg@@9@9+32, eax
	mov	DWORD PTR ?fr@?1??PopFindReplaceDlg@@9@9+36, eax
	call	DWORD PTR __imp__ReplaceTextA@4
	mov	ecx, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [ecx], 42			; 0000002aH
	mov	edx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [edx+42], 49			; 00000031H
; Line 58
	ret	0
_PopFindReplaceDlg ENDP
_TEXT	ENDS
PUBLIC	_PopFindFindText
EXTRN	__imp__SendMessageA@16:PROC
EXTRN	__imp__lstrlenA@4:PROC
EXTRN	_free:PROC
EXTRN	_strstr:PROC
EXTRN	__imp__GetWindowTextA@12:PROC
EXTRN	_malloc:PROC
EXTRN	__imp__GetWindowTextLengthA@4:PROC
; Function compile flags: /Ogtpy
;	COMDAT _PopFindFindText
_TEXT	SEGMENT
_hwndEdit$ = 8						; size = 4
_piSearchOffset$ = 12					; size = 4
_pfr$ = 16						; size = 4
_PopFindFindText PROC					; COMDAT
; Line 67
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	push	ebx
	push	ebp
; Line 73
	mov	ebp, DWORD PTR _hwndEdit$[esp+4]
	push	esi
	mov	DWORD PTR [eax], 43			; 0000002bH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	push	edi
	mov	ebx, 49					; 00000031H
	push	ebp
	mov	BYTE PTR [ecx+43], bl
	call	DWORD PTR __imp__GetWindowTextLengthA@4
	mov	edx, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [edx], 44			; 0000002cH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
; Line 75
	lea	esi, DWORD PTR [eax+1]
	push	esi
	mov	BYTE PTR [ecx+44], bl
	call	_malloc
	mov	edi, eax
	add	esp, 4
	test	edi, edi
	jne	SHORT $LN4@PopFindFin
; Line 76
	mov	edx, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [edx], 45			; 0000002dH
	mov	eax, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [eax+45], bl
	mov	ecx, DWORD PTR _csut_TFX_LastProbe
	pop	edi
	mov	DWORD PTR [ecx], 50			; 00000032H
	mov	edx, DWORD PTR _csut_TFX_CoverageBuffer
	pop	esi
	pop	ebp
	mov	BYTE PTR [edx+50], bl
	xor	eax, eax
	pop	ebx
; Line 101
	ret	0
$LN4@PopFindFin:
; Line 76
	mov	eax, DWORD PTR _csut_TFX_LastProbe
; Line 78
	push	esi
	mov	DWORD PTR [eax], 46			; 0000002eH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	push	edi
	push	ebp
	mov	BYTE PTR [ecx+46], bl
	call	DWORD PTR __imp__GetWindowTextA@12
; Line 82
	mov	edx, DWORD PTR _pfr$[esp+12]
	mov	eax, DWORD PTR [edx+16]
	mov	ecx, DWORD PTR _piSearchOffset$[esp+12]
	mov	edx, DWORD PTR [ecx]
	push	eax
	add	edx, edi
	push	edx
	call	_strstr
; Line 83
	push	edi
	mov	esi, eax
	call	_free
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 47			; 0000002fH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	add	esp, 12					; 0000000cH
	mov	BYTE PTR [ecx+47], bl
; Line 87
	test	esi, esi
	jne	SHORT $LN2@PopFindFin
; Line 88
	mov	edx, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [edx], 48			; 00000030H
	mov	eax, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [eax+48], bl
	mov	ecx, DWORD PTR _csut_TFX_LastProbe
	pop	edi
	mov	DWORD PTR [ecx], 51			; 00000033H
	mov	edx, DWORD PTR _csut_TFX_CoverageBuffer
	pop	esi
	pop	ebp
	mov	BYTE PTR [edx+51], bl
	xor	eax, eax
	pop	ebx
; Line 101
	ret	0
$LN2@PopFindFin:
; Line 88
	mov	eax, DWORD PTR _csut_TFX_LastProbe
; Line 93
	mov	edx, DWORD PTR _pfr$[esp+12]
	mov	DWORD PTR [eax], ebx
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+49], bl
	mov	eax, DWORD PTR [edx+16]
	push	eax
	sub	esi, edi
	call	DWORD PTR __imp__lstrlenA@4
	mov	ecx, DWORD PTR _piSearchOffset$[esp+12]
	add	eax, esi
; Line 97
	push	eax
	push	esi
	mov	esi, DWORD PTR __imp__SendMessageA@16
	push	177					; 000000b1H
	push	ebp
	mov	DWORD PTR [ecx], eax
	call	esi
; Line 98
	push	0
	push	0
	push	183					; 000000b7H
	push	ebp
	call	esi
; Line 100
	mov	edx, DWORD PTR _csut_TFX_LastProbe
	pop	edi
	mov	DWORD PTR [edx], 52			; 00000034H
	mov	eax, DWORD PTR _csut_TFX_CoverageBuffer
	pop	esi
	mov	BYTE PTR [eax+52], bl
	pop	ebp
	mov	eax, 1
	pop	ebx
; Line 101
	ret	0
_PopFindFindText ENDP
_TEXT	ENDS
PUBLIC	_PopFindNextText
; Function compile flags: /Ogtpy
;	COMDAT _PopFindNextText
_TEXT	SEGMENT
_fr$ = -40						; size = 40
_hwndEdit$ = 8						; size = 4
_piSearchOffset$ = 12					; size = 4
_PopFindNextText PROC					; COMDAT
; Line 110
	sub	esp, 40					; 00000028H
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 53			; 00000035H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
; Line 115
	mov	eax, DWORD PTR _piSearchOffset$[esp+36]
	lea	edx, DWORD PTR _fr$[esp+40]
	push	edx
	mov	BYTE PTR [ecx+53], 49			; 00000031H
	mov	ecx, DWORD PTR _hwndEdit$[esp+40]
	push	eax
	push	ecx
	mov	DWORD PTR _fr$[esp+68], OFFSET _szFindText
	call	_PopFindFindText
	mov	edx, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [edx], 54			; 00000036H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+54], 49			; 00000031H
; Line 116
	add	esp, 52					; 00000034H
	ret	0
_PopFindNextText ENDP
_TEXT	ENDS
PUBLIC	_PopFindReplaceText
; Function compile flags: /Ogtpy
;	COMDAT _PopFindReplaceText
_TEXT	SEGMENT
_hwndEdit$ = 8						; size = 4
_piSearchOffset$ = 12					; size = 4
_pfr$ = 16						; size = 4
_PopFindReplaceText PROC				; COMDAT
; Line 125
	mov	eax, DWORD PTR _csut_TFX_LastProbe
; Line 128
	mov	edx, DWORD PTR _piSearchOffset$[esp-4]
	push	ebx
	push	esi
	mov	esi, DWORD PTR _pfr$[esp+4]
	push	edi
	mov	edi, DWORD PTR _hwndEdit$[esp+8]
	push	esi
	mov	DWORD PTR [eax], 55			; 00000037H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	push	edx
	mov	bl, 49					; 00000031H
	push	edi
	mov	BYTE PTR [ecx+55], bl
	call	_PopFindFindText
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	SHORT $LN2@PopFindRep
; Line 129
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 56			; 00000038H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+56], bl
	mov	edx, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [edx], 58			; 0000003aH
	mov	eax, DWORD PTR _csut_TFX_CoverageBuffer
	pop	edi
	mov	BYTE PTR [eax+58], bl
	pop	esi
	xor	eax, eax
	pop	ebx
; Line 136
	ret	0
$LN2@PopFindRep:
; Line 129
	mov	ecx, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [ecx], 57			; 00000039H
	mov	edx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [edx+57], bl
; Line 133
	mov	eax, DWORD PTR [esi+20]
	push	eax
	push	0
	push	194					; 000000c2H
	push	edi
	call	DWORD PTR __imp__SendMessageA@16
; Line 135
	mov	ecx, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [ecx], 59			; 0000003bH
	mov	edx, DWORD PTR _csut_TFX_CoverageBuffer
	pop	edi
	pop	esi
	mov	BYTE PTR [edx+59], bl
	mov	eax, 1
	pop	ebx
; Line 136
	ret	0
_PopFindReplaceText ENDP
_TEXT	ENDS
PUBLIC	_PopFindValidFind
; Function compile flags: /Ogtpy
;	COMDAT _PopFindValidFind
_TEXT	SEGMENT
_PopFindValidFind PROC					; COMDAT
; Line 145
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 60			; 0000003cH
	mov	edx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	cl, 49					; 00000031H
	mov	BYTE PTR [edx+60], cl
; Line 146
	mov	edx, DWORD PTR _csut_TFX_LastProbe
	xor	eax, eax
	cmp	BYTE PTR _szFindText, al
	mov	DWORD PTR [edx], 61			; 0000003dH
	mov	edx, DWORD PTR _csut_TFX_CoverageBuffer
	setne	al
	mov	BYTE PTR [edx+61], cl
; Line 147
	ret	0
_PopFindValidFind ENDP
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT _PopFindFindDlg_csut0
_TEXT	SEGMENT
_hwnd$ = 8						; size = 4
_csutp$ = 8						; size = 4
_PopFindFindDlg_csut0 PROC				; COMDAT
; File f:\20120709_enterprise_ct_v2.0_workspace\vc2008_poppad3_c\unittest\popfindfinddlg_csut0.c
; Line 19
	mov	eax, DWORD PTR _csutp$[esp-4]
	mov	cl, BYTE PTR [eax]
; Line 21
	mov	edx, DWORD PTR _hwnd$[esp-4]
	mov	BYTE PTR _szFindText, cl
	mov	DWORD PTR _csutp$[esp-4], edx
	jmp	_PopFindFindDlg
_PopFindFindDlg_csut0 ENDP
_TEXT	ENDS
PUBLIC	??_C@_0BF@HDOOFCKD@PopFindFindText_ret0?$AA@	; `string'
EXTRN	_csut_TFX_writeIntOutput:PROC
;	COMDAT ??_C@_0BF@HDOOFCKD@PopFindFindText_ret0?$AA@
; File f:\20120709_enterprise_ct_v2.0_workspace\vc2008_poppad3_c\unittest\popfindfindtext_csut0.c
CONST	SEGMENT
??_C@_0BF@HDOOFCKD@PopFindFindText_ret0?$AA@ DB 'PopFindFindText_ret0', 00H ; `string'
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT _PopFindFindText_csut0
_TEXT	SEGMENT
_mem10$ = -44						; size = 4
_mem11$ = -40						; size = 40
_hwndEdit$ = 8						; size = 4
_mem12$ = 8						; size = 1
_csutp$ = 8						; size = 4
_PopFindFindText_csut0 PROC				; COMDAT
; Line 17
	sub	esp, 44					; 0000002cH
; Line 28
	lea	eax, DWORD PTR _mem12$[esp+40]
	mov	DWORD PTR _mem11$[esp+60], eax
; Line 30
	mov	eax, DWORD PTR _csutp$[esp+40]
	mov	ecx, DWORD PTR [eax]
; Line 31
	mov	dl, BYTE PTR [eax+4]
; Line 33
	lea	eax, DWORD PTR _mem11$[esp+44]
	mov	DWORD PTR _mem10$[esp+44], ecx
	push	eax
	lea	ecx, DWORD PTR _mem10$[esp+48]
	mov	BYTE PTR _mem12$[esp+44], dl
	mov	edx, DWORD PTR _hwndEdit$[esp+44]
	push	ecx
	push	edx
	call	_PopFindFindText
; Line 34
	push	0
	push	0
	cdq
	push	4
	push	edx
	push	eax
	push	OFFSET ??_C@_0BF@HDOOFCKD@PopFindFindText_ret0?$AA@
	call	_csut_TFX_writeIntOutput
; Line 36
	add	esp, 80					; 00000050H
	ret	0
_PopFindFindText_csut0 ENDP
_TEXT	ENDS
PUBLIC	??_C@_0BF@JHNOHJLJ@PopFindNextText_ret0?$AA@	; `string'
;	COMDAT ??_C@_0BF@JHNOHJLJ@PopFindNextText_ret0?$AA@
; File f:\20120709_enterprise_ct_v2.0_workspace\vc2008_poppad3_c\unittest\popfindnexttext_csut0.c
CONST	SEGMENT
??_C@_0BF@JHNOHJLJ@PopFindNextText_ret0?$AA@ DB 'PopFindNextText_ret0', 00H ; `string'
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT _PopFindNextText_csut0
_TEXT	SEGMENT
_hwndEdit$ = 8						; size = 4
_mem13$ = 8						; size = 4
_csutp$ = 8						; size = 4
_PopFindNextText_csut0 PROC				; COMDAT
; Line 25
	mov	eax, DWORD PTR _csutp$[esp-4]
	mov	ecx, DWORD PTR [eax]
; Line 26
	mov	dl, BYTE PTR [eax+4]
; Line 28
	lea	eax, DWORD PTR _mem13$[esp-4]
	mov	DWORD PTR _mem13$[esp-4], ecx
	mov	ecx, DWORD PTR _hwndEdit$[esp-4]
	push	eax
	push	ecx
	mov	BYTE PTR _szFindText, dl
	call	_PopFindNextText
; Line 29
	push	0
	push	0
	cdq
	push	4
	push	edx
	push	eax
	push	OFFSET ??_C@_0BF@JHNOHJLJ@PopFindNextText_ret0?$AA@
	call	_csut_TFX_writeIntOutput
	add	esp, 32					; 00000020H
; Line 31
	ret	0
_PopFindNextText_csut0 ENDP
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT _PopFindReplaceDlg_csut0
_TEXT	SEGMENT
_hwnd$ = 8						; size = 4
_csutp$ = 8						; size = 4
_PopFindReplaceDlg_csut0 PROC				; COMDAT
; File f:\20120709_enterprise_ct_v2.0_workspace\vc2008_poppad3_c\unittest\popfindreplacedlg_csut0.c
; Line 20
	mov	eax, DWORD PTR _csutp$[esp-4]
	mov	cl, BYTE PTR [eax]
	mov	BYTE PTR _szFindText, cl
; Line 21
	mov	dl, BYTE PTR [eax+1]
; Line 23
	mov	eax, DWORD PTR _hwnd$[esp-4]
	mov	BYTE PTR _szReplText, dl
	mov	DWORD PTR _csutp$[esp-4], eax
	jmp	_PopFindReplaceDlg
_PopFindReplaceDlg_csut0 ENDP
_TEXT	ENDS
PUBLIC	??_C@_0BI@LGAOFIDJ@PopFindReplaceText_ret0?$AA@	; `string'
;	COMDAT ??_C@_0BI@LGAOFIDJ@PopFindReplaceText_ret0?$AA@
; File f:\20120709_enterprise_ct_v2.0_workspace\vc2008_poppad3_c\unittest\popfindreplacetext_csut0.c
CONST	SEGMENT
??_C@_0BI@LGAOFIDJ@PopFindReplaceText_ret0?$AA@ DB 'PopFindReplaceText_re'
	DB	't0', 00H					; `string'
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT _PopFindReplaceText_csut0
_TEXT	SEGMENT
_mem14$ = -44						; size = 4
_mem15$ = -40						; size = 40
_hwndEdit$ = 8						; size = 4
_mem16$ = 8						; size = 1
_csutp$ = 8						; size = 4
_PopFindReplaceText_csut0 PROC				; COMDAT
; Line 17
	sub	esp, 44					; 0000002cH
; Line 28
	lea	eax, DWORD PTR _mem16$[esp+40]
	mov	DWORD PTR _mem15$[esp+64], eax
; Line 30
	mov	eax, DWORD PTR _csutp$[esp+40]
	mov	ecx, DWORD PTR [eax]
; Line 31
	mov	dl, BYTE PTR [eax+4]
; Line 33
	lea	eax, DWORD PTR _mem15$[esp+44]
	mov	DWORD PTR _mem14$[esp+44], ecx
	push	eax
	lea	ecx, DWORD PTR _mem14$[esp+48]
	mov	BYTE PTR _mem16$[esp+44], dl
	mov	edx, DWORD PTR _hwndEdit$[esp+44]
	push	ecx
	push	edx
	call	_PopFindReplaceText
; Line 34
	push	0
	push	0
	cdq
	push	4
	push	edx
	push	eax
	push	OFFSET ??_C@_0BI@LGAOFIDJ@PopFindReplaceText_ret0?$AA@
	call	_csut_TFX_writeIntOutput
; Line 36
	add	esp, 80					; 00000050H
	ret	0
_PopFindReplaceText_csut0 ENDP
_TEXT	ENDS
PUBLIC	??_C@_0BG@JPECCOAF@PopFindValidFind_ret0?$AA@	; `string'
;	COMDAT ??_C@_0BG@JPECCOAF@PopFindValidFind_ret0?$AA@
; File f:\20120709_enterprise_ct_v2.0_workspace\vc2008_poppad3_c\unittest\popfindvalidfind_csut0.c
CONST	SEGMENT
??_C@_0BG@JPECCOAF@PopFindValidFind_ret0?$AA@ DB 'PopFindValidFind_ret0', 00H ; `string'
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT _PopFindValidFind_csut0
_TEXT	SEGMENT
_csutp$ = 8						; size = 4
_PopFindValidFind_csut0 PROC				; COMDAT
; Line 19
	mov	eax, DWORD PTR _csutp$[esp-4]
	mov	cl, BYTE PTR [eax]
	mov	BYTE PTR _szFindText, cl
; Line 21
	call	_PopFindValidFind
; Line 22
	push	0
	push	0
	cdq
	push	4
	push	edx
	push	eax
	push	OFFSET ??_C@_0BG@JPECCOAF@PopFindValidFind_ret0?$AA@
	call	_csut_TFX_writeIntOutput
	add	esp, 24					; 00000018H
; Line 24
	ret	0
_PopFindValidFind_csut0 ENDP
_TEXT	ENDS
END
