; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	F:\20120709_Enterprise_CT_V2.0_workspace\VC2008_PopPad3_c\.csdata\src\build\PopPrnt0_10.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BP@HJDNDHEP@struct?5PopPrntPrintFile_csut0p?$AA@ ; `string'
PUBLIC	??_C@_0BH@JMKNEPJP@PopPrntPrintFile_csut0?$AA@	; `string'
PUBLIC	_PopPrntPrintFile_csut0
PUBLIC	__TFX_testFunctionsFor_5629499534213120
_DATA	SEGMENT
__TFX_testFunctionsFor_5629499534213120 DD 04H
	DD	FLAT:_PopPrntPrintFile_csut0
	DD	FLAT:??_C@_0BH@JMKNEPJP@PopPrntPrintFile_csut0?$AA@
	DD	FLAT:??_C@_0BP@HJDNDHEP@struct?5PopPrntPrintFile_csut0p?$AA@
	DD	08H
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
_DATA	ENDS
;	COMDAT ??_C@_0BP@HJDNDHEP@struct?5PopPrntPrintFile_csut0p?$AA@
CONST	SEGMENT
??_C@_0BP@HJDNDHEP@struct?5PopPrntPrintFile_csut0p?$AA@ DB 'struct PopPrn'
	DB	'tPrintFile_csut0p', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BH@JMKNEPJP@PopPrntPrintFile_csut0?$AA@
CONST	SEGMENT
??_C@_0BH@JMKNEPJP@PopPrntPrintFile_csut0?$AA@ DB 'PopPrntPrintFile_csut0'
	DB	00H						; `string'
CONST	ENDS
PUBLIC	_PopPrntPrintFile
EXTRN	_csut_TFX_CoverageBuffer:DWORD
EXTRN	_csut_TFX_LastProbe:DWORD
; Function compile flags: /Ogtpy
;	COMDAT _PopPrntPrintFile
_TEXT	SEGMENT
_hInst$ = 8						; size = 4
_hwnd$ = 12						; size = 4
_hwndEdit$ = 16						; size = 4
_pstrTitleName$ = 20					; size = 4
_PopPrntPrintFile PROC					; COMDAT
; File d:\open source\vs2008\c\poppad3\popprnt0.c
; Line 11
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 253			; 000000fdH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	al, 49					; 00000031H
	mov	BYTE PTR [ecx+253], al
; Line 12
	mov	edx, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [edx], 254			; 000000feH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+254], al
	xor	eax, eax
; Line 13
	ret	0
_PopPrntPrintFile ENDP
_TEXT	ENDS
PUBLIC	??_C@_0BG@DPLFFACP@PopPrntPrintFile_ret0?$AA@	; `string'
EXTRN	_csut_TFX_writeIntOutput:PROC
;	COMDAT ??_C@_0BG@DPLFFACP@PopPrntPrintFile_ret0?$AA@
; File f:\20120709_enterprise_ct_v2.0_workspace\vc2008_poppad3_c\unittest\popprntprintfile_csut0.c
CONST	SEGMENT
??_C@_0BG@DPLFFACP@PopPrntPrintFile_ret0?$AA@ DB 'PopPrntPrintFile_ret0', 00H ; `string'
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT _PopPrntPrintFile_csut0
_TEXT	SEGMENT
_mem17$ = -5						; size = 1
_hInst$ = -4						; size = 4
_hwnd$ = -4						; size = 4
_hwndEdit$ = -4						; size = 4
_csutp$ = 8						; size = 4
_PopPrntPrintFile_csut0 PROC				; COMDAT
; Line 28
	mov	ecx, DWORD PTR _hwndEdit$[esp]
	mov	edx, DWORD PTR _hwnd$[esp]
	sub	esp, 8
	lea	eax, DWORD PTR _mem17$[esp+8]
	push	eax
	mov	eax, DWORD PTR _hInst$[esp+12]
	push	ecx
	push	edx
	push	eax
	call	_PopPrntPrintFile
; Line 29
	push	0
	push	0
	cdq
	push	4
	push	edx
	push	eax
	push	OFFSET ??_C@_0BG@DPLFFACP@PopPrntPrintFile_ret0?$AA@
	call	_csut_TFX_writeIntOutput
; Line 31
	add	esp, 48					; 00000030H
	ret	0
_PopPrntPrintFile_csut0 ENDP
_TEXT	ENDS
END
