; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	F:\20120709_Enterprise_CT_V2.0_workspace\kljl\.csdata\src\build\PopFile_1.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

PUBLIC	__TFX_SuiteList
EXTRN	__TFX_testFunctionsFor_562949953421312:BYTE
EXTRN	__TFX_testFunctionsFor_281474976710656:BYTE
_DATA	SEGMENT
?szFilter@?1??PopFileInitialize@@9@9 DB 'T', 00H, 'e', 00H, 'x', 00H, 't', 00H
	DB	' ', 00H, 'F', 00H, 'i', 00H, 'l', 00H, 'e', 00H, 's', 00H, ' '
	DB	00H, '(', 00H, '*', 00H, '.', 00H, 'T', 00H, 'X', 00H, 'T', 00H
	DB	')', 00H, 00H, 00H, '*', 00H, '.', 00H, 't', 00H, 'x', 00H, 't'
	DB	00H, 00H, 00H, 'A', 00H, 'S', 00H, 'C', 00H, 'I', 00H, 'I', 00H
	DB	' ', 00H, 'F', 00H, 'i', 00H, 'l', 00H, 'e', 00H, 's', 00H, ' '
	DB	00H, '(', 00H, '*', 00H, '.', 00H, 'A', 00H, 'S', 00H, 'C', 00H
	DB	')', 00H, 00H, 00H, '*', 00H, '.', 00H, 'a', 00H, 's', 00H, 'c'
	DB	00H, 00H, 00H, 'A', 00H, 'l', 00H, 'l', 00H, ' ', 00H, 'F', 00H
	DB	'i', 00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, '*'
	DB	00H, '.', 00H, '*', 00H, ')', 00H, 00H, 00H, '*', 00H, '.', 00H
	DB	'*', 00H, 00H, 00H, 00H, 00H, 00H, 00H	; `PopFileInitialize'::`2'::szFilter
	ORG $+2
__TFX_SuiteList DD FLAT:__TFX_testFunctionsFor_281474976710656
	DD	FLAT:__TFX_testFunctionsFor_562949953421312
	DD	00H
_DATA	ENDS
PUBLIC	??_C@_17LBOLAHJL@?$AAt?$AAx?$AAt?$AA?$AA@	; `string'
PUBLIC	_PopFileInitialize
EXTRN	_csut_TFX_CoverageBuffer:DWORD
EXTRN	_csut_TFX_LastProbe:DWORD
_BSS	SEGMENT
_ofn	DB	058H DUP (?)
_BSS	ENDS
;	COMDAT ??_C@_17LBOLAHJL@?$AAt?$AAx?$AAt?$AA?$AA@
; File d:\open source\vs2008\c\poppad3\popfile.c
CONST	SEGMENT
??_C@_17LBOLAHJL@?$AAt?$AAx?$AAt?$AA?$AA@ DB 't', 00H, 'x', 00H, 't', 00H
	DB	00H, 00H					; `string'
; Function compile flags: /Odtp /ZI
CONST	ENDS
;	COMDAT _PopFileInitialize
_TEXT	SEGMENT
_codescroll_4294968638$ = -4				; size = 4
_hwnd$ = 8						; size = 4
_PopFileInitialize PROC					; COMDAT
; Line 13
	push	ebp
	mov	ebp, esp
	sub	esp, 68					; 00000044H
	push	ebx
	push	esi
	push	edi
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 0
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx], 49			; 00000031H
	mov	DWORD PTR _codescroll_4294968638$[ebp], 0
; Line 18
	mov	DWORD PTR _ofn, 88			; 00000058H
; Line 19
	mov	eax, DWORD PTR _hwnd$[ebp]
	mov	DWORD PTR _ofn+4, eax
; Line 20
	mov	DWORD PTR _ofn+8, 0
; Line 21
	mov	DWORD PTR _ofn+12, OFFSET ?szFilter@?1??PopFileInitialize@@9@9
; Line 22
	mov	DWORD PTR _ofn+16, 0
; Line 23
	mov	DWORD PTR _ofn+20, 0
; Line 24
	mov	DWORD PTR _ofn+24, 0
; Line 25
	mov	DWORD PTR _ofn+28, 0
; Line 26
	mov	DWORD PTR _ofn+32, 260			; 00000104H
; Line 27
	mov	DWORD PTR _ofn+36, 0
; Line 28
	mov	DWORD PTR _ofn+40, 260			; 00000104H
; Line 29
	mov	DWORD PTR _ofn+44, 0
; Line 30
	mov	DWORD PTR _ofn+48, 0
; Line 31
	mov	DWORD PTR _ofn+52, 0
; Line 32
	xor	eax, eax
	mov	WORD PTR _ofn+56, ax
; Line 33
	xor	eax, eax
	mov	WORD PTR _ofn+58, ax
; Line 34
	mov	DWORD PTR _ofn+60, OFFSET ??_C@_17LBOLAHJL@?$AAt?$AAx?$AAt?$AA?$AA@
; Line 35
	mov	DWORD PTR _ofn+64, 0
; Line 36
	mov	DWORD PTR _ofn+68, 0
; Line 37
	mov	DWORD PTR _ofn+72, 0
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 1
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+1], 49			; 00000031H
; Line 38
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_PopFileInitialize ENDP
_TEXT	ENDS
PUBLIC	_PopFileOpenDlg
EXTRN	__imp__GetOpenFileNameW@4:PROC
; Function compile flags: /Odtp /ZI
;	COMDAT _PopFileOpenDlg
_TEXT	SEGMENT
_csut_ret$77160 = -4					; size = 4
_hwnd$ = 8						; size = 4
_pstrFileName$ = 12					; size = 4
_pstrTitleName$ = 16					; size = 4
_PopFileOpenDlg PROC					; COMDAT
; Line 47
	push	ebp
	mov	ebp, esp
	sub	esp, 68					; 00000044H
	push	ebx
	push	esi
	push	edi
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 2
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+2], 49			; 00000031H
; Line 48
	mov	eax, DWORD PTR _hwnd$[ebp]
	mov	DWORD PTR _ofn+4, eax
; Line 49
	mov	eax, DWORD PTR _pstrFileName$[ebp]
	mov	DWORD PTR _ofn+28, eax
; Line 50
	mov	eax, DWORD PTR _pstrTitleName$[ebp]
	mov	DWORD PTR _ofn+36, eax
; Line 51
	mov	DWORD PTR _ofn+52, 8196			; 00002004H
; Line 53
	push	OFFSET _ofn
	call	DWORD PTR __imp__GetOpenFileNameW@4
	mov	DWORD PTR _csut_ret$77160[ebp], eax
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 3
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+3], 49			; 00000031H
	mov	eax, DWORD PTR _csut_ret$77160[ebp]
; Line 54
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_PopFileOpenDlg ENDP
_TEXT	ENDS
PUBLIC	_PopFileSaveDlg
EXTRN	__imp__GetSaveFileNameW@4:PROC
; Function compile flags: /Odtp /ZI
;	COMDAT _PopFileSaveDlg
_TEXT	SEGMENT
_csut_ret$77169 = -4					; size = 4
_hwnd$ = 8						; size = 4
_pstrFileName$ = 12					; size = 4
_pstrTitleName$ = 16					; size = 4
_PopFileSaveDlg PROC					; COMDAT
; Line 63
	push	ebp
	mov	ebp, esp
	sub	esp, 68					; 00000044H
	push	ebx
	push	esi
	push	edi
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 4
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+4], 49			; 00000031H
; Line 64
	mov	eax, DWORD PTR _hwnd$[ebp]
	mov	DWORD PTR _ofn+4, eax
; Line 65
	mov	eax, DWORD PTR _pstrFileName$[ebp]
	mov	DWORD PTR _ofn+28, eax
; Line 66
	mov	eax, DWORD PTR _pstrTitleName$[ebp]
	mov	DWORD PTR _ofn+36, eax
; Line 67
	mov	DWORD PTR _ofn+52, 2
; Line 69
	push	OFFSET _ofn
	call	DWORD PTR __imp__GetSaveFileNameW@4
	mov	DWORD PTR _csut_ret$77169[ebp], eax
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 5
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+5], 49			; 00000031H
	mov	eax, DWORD PTR _csut_ret$77169[ebp]
; Line 70
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_PopFileSaveDlg ENDP
_TEXT	ENDS
PUBLIC	_PopFileRead
EXTRN	_free:PROC
EXTRN	__imp__SetWindowTextW@8:PROC
EXTRN	__imp__MultiByteToWideChar@24:PROC
EXTRN	__imp__lstrcpyW@8:PROC
EXTRN	__imp__IsTextUnicode@12:PROC
EXTRN	__imp__CloseHandle@4:PROC
EXTRN	__imp__ReadFile@20:PROC
EXTRN	_malloc:PROC
EXTRN	__imp__GetFileSize@8:PROC
EXTRN	__imp__CreateFileW@28:PROC
; Function compile flags: /Odtp /ZI
;	COMDAT _PopFileRead
_TEXT	SEGMENT
tv144 = -108						; size = 4
_pConv$ = -40						; size = 4
_pText$ = -36						; size = 4
_pBuffer$ = -32						; size = 4
_iUniTest$ = -28					; size = 4
_iFileLength$ = -24					; size = 4
_i$ = -20						; size = 4
_hFile$ = -16						; size = 4
_dwBytesRead$ = -12					; size = 4
_bySwap$ = -5						; size = 1
_codescroll_4294968639$ = -4				; size = 4
_hwndEdit$ = 8						; size = 4
_pstrFileName$ = 12					; size = 4
_PopFileRead PROC					; COMDAT
; Line 79
	push	ebp
	mov	ebp, esp
	sub	esp, 108				; 0000006cH
	push	ebx
	push	esi
	push	edi
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 6
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+6], 49			; 00000031H
	mov	DWORD PTR _codescroll_4294968639$[ebp], 0
; Line 84
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 7
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+7], 49			; 00000031H
; Line 90
	push	0
	push	0
	push	3
	push	0
	push	1
	push	-2147483648				; 80000000H
	mov	eax, DWORD PTR _pstrFileName$[ebp]
	push	eax
	call	DWORD PTR __imp__CreateFileW@28
	mov	DWORD PTR _hFile$[ebp], eax
	cmp	DWORD PTR _hFile$[ebp], -1
	jne	SHORT $LN9@PopFileRea
; Line 91
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 8
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+8], 49			; 00000031H
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 23			; 00000017H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+23], 49			; 00000031H
	xor	eax, eax
	jmp	$LN10@PopFileRea
	jmp	SHORT $LN8@PopFileRea
$LN9@PopFileRea:
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 9
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+9], 49			; 00000031H
$LN8@PopFileRea:
; Line 96
	push	0
	mov	eax, DWORD PTR _hFile$[ebp]
	push	eax
	call	DWORD PTR __imp__GetFileSize@8
	mov	DWORD PTR _iFileLength$[ebp], eax
; Line 97
	mov	eax, DWORD PTR _iFileLength$[ebp]
	add	eax, 2
	push	eax
	call	_malloc
	add	esp, 4
	mov	DWORD PTR _pBuffer$[ebp], eax
; Line 101
	push	0
	lea	eax, DWORD PTR _dwBytesRead$[ebp]
	push	eax
	mov	ecx, DWORD PTR _iFileLength$[ebp]
	push	ecx
	mov	edx, DWORD PTR _pBuffer$[ebp]
	push	edx
	mov	eax, DWORD PTR _hFile$[ebp]
	push	eax
	call	DWORD PTR __imp__ReadFile@20
; Line 102
	mov	eax, DWORD PTR _hFile$[ebp]
	push	eax
	call	DWORD PTR __imp__CloseHandle@4
; Line 103
	mov	eax, DWORD PTR _pBuffer$[ebp]
	add	eax, DWORD PTR _iFileLength$[ebp]
	mov	BYTE PTR [eax], 0
; Line 104
	mov	eax, DWORD PTR _pBuffer$[ebp]
	add	eax, DWORD PTR _iFileLength$[ebp]
	mov	BYTE PTR [eax+1], 0
; Line 108
	mov	DWORD PTR _iUniTest$[ebp], 136		; 00000088H
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 10			; 0000000aH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+10], 49			; 00000031H
; Line 110
	lea	eax, DWORD PTR _iUniTest$[ebp]
	push	eax
	mov	ecx, DWORD PTR _iFileLength$[ebp]
	push	ecx
	mov	edx, DWORD PTR _pBuffer$[ebp]
	push	edx
	call	DWORD PTR __imp__IsTextUnicode@12
	test	eax, eax
	je	$LN7@PopFileRea
; Line 111
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 21			; 00000015H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+21], 49			; 00000031H
; Line 112
	mov	eax, DWORD PTR _pBuffer$[ebp]
	add	eax, 2
	mov	DWORD PTR _pText$[ebp], eax
; Line 113
	mov	eax, DWORD PTR _iFileLength$[ebp]
	sub	eax, 2
	mov	DWORD PTR _iFileLength$[ebp], eax
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 11			; 0000000bH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+11], 49			; 00000031H
; Line 115
	mov	eax, DWORD PTR _iUniTest$[ebp]
	and	eax, 128				; 00000080H
	je	$LN6@PopFileRea
; Line 116
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 17			; 00000011H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+17], 49			; 00000031H
; Line 117
	mov	DWORD PTR _i$[ebp], 0
	jmp	SHORT $LN5@PopFileRea
$LN4@PopFileRea:
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, 1
	mov	DWORD PTR _i$[ebp], eax
$LN5@PopFileRea:
	mov	eax, DWORD PTR _csut_TFX_CoverageBuffer
	movzx	ecx, BYTE PTR [eax+14]
	cmp	ecx, 49					; 00000031H
	jne	SHORT $LN12@PopFileRea
	mov	edx, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [edx], 16			; 00000010H
	mov	eax, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [eax+16], 49			; 00000031H
	mov	DWORD PTR tv144[ebp], 49		; 00000031H
	jmp	SHORT $LN13@PopFileRea
$LN12@PopFileRea:
	mov	ecx, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [ecx], 13			; 0000000dH
	mov	edx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [edx+13], 49			; 00000031H
	mov	DWORD PTR tv144[ebp], 49		; 00000031H
$LN13@PopFileRea:
	mov	eax, DWORD PTR _iFileLength$[ebp]
	cdq
	sub	eax, edx
	sar	eax, 1
	cmp	DWORD PTR _i$[ebp], eax
	jge	SHORT $LN3@PopFileRea
; Line 118
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 14			; 0000000eH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+14], 49			; 00000031H
; Line 119
	mov	eax, DWORD PTR _i$[ebp]
	mov	ecx, DWORD PTR _pText$[ebp]
	mov	dl, BYTE PTR [ecx+eax*2]
	mov	BYTE PTR _bySwap$[ebp], dl
; Line 120
	mov	eax, DWORD PTR _i$[ebp]
	mov	ecx, DWORD PTR _pText$[ebp]
	mov	edx, DWORD PTR _i$[ebp]
	mov	esi, DWORD PTR _pText$[ebp]
	mov	dl, BYTE PTR [esi+edx*2+1]
	mov	BYTE PTR [ecx+eax*2], dl
; Line 121
	mov	eax, DWORD PTR _i$[ebp]
	mov	ecx, DWORD PTR _pText$[ebp]
	mov	dl, BYTE PTR _bySwap$[ebp]
	mov	BYTE PTR [ecx+eax*2+1], dl
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 12			; 0000000cH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+12], 49			; 00000031H
	jmp	$LN4@PopFileRea
$LN3@PopFileRea:
; Line 122
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 15			; 0000000fH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+15], 49			; 00000031H
	jmp	SHORT $LN2@PopFileRea
$LN6@PopFileRea:
; Line 123
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 18			; 00000012H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+18], 49			; 00000031H
$LN2@PopFileRea:
; Line 127
	mov	eax, DWORD PTR _iFileLength$[ebp]
	add	eax, 2
	push	eax
	call	_malloc
	add	esp, 4
	mov	DWORD PTR _pConv$[ebp], eax
; Line 138
	mov	eax, DWORD PTR _pText$[ebp]
	push	eax
	mov	ecx, DWORD PTR _pConv$[ebp]
	push	ecx
	call	DWORD PTR __imp__lstrcpyW@8
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 19			; 00000013H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+19], 49			; 00000031H
; Line 122
	jmp	SHORT $LN1@PopFileRea
$LN7@PopFileRea:
; Line 123
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 22			; 00000016H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+22], 49			; 00000031H
; Line 124
	mov	eax, DWORD PTR _pBuffer$[ebp]
	mov	DWORD PTR _pText$[ebp], eax
; Line 128
	mov	eax, DWORD PTR _iFileLength$[ebp]
	lea	ecx, DWORD PTR [eax+eax+2]
	push	ecx
	call	_malloc
	add	esp, 4
	mov	DWORD PTR _pConv$[ebp], eax
; Line 134
	mov	eax, DWORD PTR _iFileLength$[ebp]
	add	eax, 1
	push	eax
	mov	ecx, DWORD PTR _pConv$[ebp]
	push	ecx
	push	-1
	mov	edx, DWORD PTR _pText$[ebp]
	push	edx
	push	0
	push	0
	call	DWORD PTR __imp__MultiByteToWideChar@24
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 20			; 00000014H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+20], 49			; 00000031H
$LN1@PopFileRea:
; Line 142
	mov	eax, DWORD PTR _pConv$[ebp]
	push	eax
	mov	ecx, DWORD PTR _hwndEdit$[ebp]
	push	ecx
	call	DWORD PTR __imp__SetWindowTextW@8
; Line 143
	mov	eax, DWORD PTR _pBuffer$[ebp]
	push	eax
	call	_free
	add	esp, 4
; Line 144
	mov	eax, DWORD PTR _pConv$[ebp]
	push	eax
	call	_free
	add	esp, 4
; Line 146
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 24			; 00000018H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+24], 49			; 00000031H
	mov	eax, 1
$LN10@PopFileRea:
; Line 147
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_PopFileRead ENDP
_TEXT	ENDS
PUBLIC	_PopFileWrite
EXTRN	__imp__GetWindowTextW@12:PROC
EXTRN	__imp__WriteFile@20:PROC
EXTRN	__imp__GetWindowTextLengthW@4:PROC
; Function compile flags: /Odtp /ZI
;	COMDAT _PopFileWrite
_TEXT	SEGMENT
_wByteOrderMark$ = -24					; size = 2
_pstrBuffer$ = -20					; size = 4
_iLength$ = -16						; size = 4
_hFile$ = -12						; size = 4
_dwBytesWritten$ = -8					; size = 4
_codescroll_4294968640$ = -4				; size = 4
_hwndEdit$ = 8						; size = 4
_pstrFileName$ = 12					; size = 4
_PopFileWrite PROC					; COMDAT
; Line 156
	push	ebp
	mov	ebp, esp
	sub	esp, 88					; 00000058H
	push	ebx
	push	esi
	push	edi
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 25			; 00000019H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+25], 49			; 00000031H
	mov	DWORD PTR _codescroll_4294968640$[ebp], 0
; Line 161
	mov	eax, 65279				; 0000feffH
	mov	WORD PTR _wByteOrderMark$[ebp], ax
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 26			; 0000001aH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+26], 49			; 00000031H
; Line 167
	push	0
	push	0
	push	2
	push	0
	push	0
	push	1073741824				; 40000000H
	mov	eax, DWORD PTR _pstrFileName$[ebp]
	push	eax
	call	DWORD PTR __imp__CreateFileW@28
	mov	DWORD PTR _hFile$[ebp], eax
	cmp	DWORD PTR _hFile$[ebp], -1
	jne	SHORT $LN6@PopFileWri
; Line 168
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 27			; 0000001bH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+27], 49			; 00000031H
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 35			; 00000023H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+35], 49			; 00000031H
	xor	eax, eax
	jmp	$LN7@PopFileWri
	jmp	SHORT $LN5@PopFileWri
$LN6@PopFileWri:
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 28			; 0000001cH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+28], 49			; 00000031H
$LN5@PopFileWri:
; Line 173
	mov	eax, DWORD PTR _hwndEdit$[ebp]
	push	eax
	call	DWORD PTR __imp__GetWindowTextLengthW@4
	mov	DWORD PTR _iLength$[ebp], eax
; Line 174
	mov	eax, DWORD PTR _iLength$[ebp]
	lea	ecx, DWORD PTR [eax+eax+2]
	push	ecx
	call	_malloc
	add	esp, 4
	mov	DWORD PTR _pstrBuffer$[ebp], eax
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 29			; 0000001dH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+29], 49			; 00000031H
; Line 176
	cmp	DWORD PTR _pstrBuffer$[ebp], 0
	jne	SHORT $LN4@PopFileWri
; Line 177
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 30			; 0000001eH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+30], 49			; 00000031H
; Line 178
	mov	eax, DWORD PTR _hFile$[ebp]
	push	eax
	call	DWORD PTR __imp__CloseHandle@4
; Line 179
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 36			; 00000024H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+36], 49			; 00000031H
	xor	eax, eax
	jmp	$LN7@PopFileWri
	jmp	SHORT $LN3@PopFileWri
$LN4@PopFileWri:
; Line 180
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 31			; 0000001fH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+31], 49			; 00000031H
$LN3@PopFileWri:
; Line 186
	push	0
	lea	eax, DWORD PTR _dwBytesWritten$[ebp]
	push	eax
	push	2
	lea	ecx, DWORD PTR _wByteOrderMark$[ebp]
	push	ecx
	mov	edx, DWORD PTR _hFile$[ebp]
	push	edx
	call	DWORD PTR __imp__WriteFile@20
; Line 185
	mov	eax, DWORD PTR _iLength$[ebp]
	add	eax, 1
	push	eax
	mov	ecx, DWORD PTR _pstrBuffer$[ebp]
	push	ecx
	mov	edx, DWORD PTR _hwndEdit$[ebp]
	push	edx
	call	DWORD PTR __imp__GetWindowTextW@12
; Line 187
	push	0
	lea	eax, DWORD PTR _dwBytesWritten$[ebp]
	push	eax
	mov	ecx, DWORD PTR _iLength$[ebp]
	shl	ecx, 1
	push	ecx
	mov	edx, DWORD PTR _pstrBuffer$[ebp]
	push	edx
	mov	eax, DWORD PTR _hFile$[ebp]
	push	eax
	call	DWORD PTR __imp__WriteFile@20
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 32			; 00000020H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+32], 49			; 00000031H
; Line 189
	mov	eax, DWORD PTR _iLength$[ebp]
	shl	eax, 1
	cmp	eax, DWORD PTR _dwBytesWritten$[ebp]
	je	SHORT $LN2@PopFileWri
; Line 190
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 33			; 00000021H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+33], 49			; 00000031H
; Line 191
	mov	eax, DWORD PTR _hFile$[ebp]
	push	eax
	call	DWORD PTR __imp__CloseHandle@4
; Line 192
	mov	eax, DWORD PTR _pstrBuffer$[ebp]
	push	eax
	call	_free
	add	esp, 4
; Line 193
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 37			; 00000025H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+37], 49			; 00000031H
	xor	eax, eax
	jmp	SHORT $LN7@PopFileWri
	jmp	SHORT $LN1@PopFileWri
$LN2@PopFileWri:
; Line 194
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 34			; 00000022H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+34], 49			; 00000031H
$LN1@PopFileWri:
; Line 196
	mov	eax, DWORD PTR _hFile$[ebp]
	push	eax
	call	DWORD PTR __imp__CloseHandle@4
; Line 197
	mov	eax, DWORD PTR _pstrBuffer$[ebp]
	push	eax
	call	_free
	add	esp, 4
; Line 199
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 38			; 00000026H
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+38], 49			; 00000031H
	mov	eax, 1
$LN7@PopFileWri:
; Line 200
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_PopFileWrite ENDP
_TEXT	ENDS
END
