; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	F:\20120709_Enterprise_CT_V2.0_workspace\kljl\.csdata\src\build\PopPrnt0_5.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

PUBLIC	_PopPrntPrintFile
EXTRN	_csut_TFX_CoverageBuffer:DWORD
EXTRN	_csut_TFX_LastProbe:DWORD
; Function compile flags: /Odtp /ZI
;	COMDAT _PopPrntPrintFile
_TEXT	SEGMENT
_hInst$ = 8						; size = 4
_hwnd$ = 12						; size = 4
_hwndEdit$ = 16						; size = 4
_pstrTitleName$ = 20					; size = 4
_PopPrntPrintFile PROC					; COMDAT
; File d:\open source\vs2008\c\poppad3\popprnt0.c
; Line 11
	push	ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	push	ebx
	push	esi
	push	edi
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 253			; 000000fdH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+253], 49			; 00000031H
; Line 12
	mov	eax, DWORD PTR _csut_TFX_LastProbe
	mov	DWORD PTR [eax], 254			; 000000feH
	mov	ecx, DWORD PTR _csut_TFX_CoverageBuffer
	mov	BYTE PTR [ecx+254], 49			; 00000031H
	xor	eax, eax
; Line 13
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_PopPrntPrintFile ENDP
_TEXT	ENDS
END
